### PR TITLE
st/2018-03/01

### PR DESCRIPTION
**Pull request by RyzorBent**
### Pull Request check-list

_Please make sure to review and check all of these items:_

- [ ] Have you run `node compile.js -b test -l [language] -q [quarter]`?
- [ ] Have you checked for semicolons in the titles?

_NOTE: these things are not required to open a PR and can be done
afterwards / while the PR is open._

For example, `node compile.js -b test -l en -q 2018-02`.

### Description of contribution
Hi Team, this is my very first github pull request, so i'm just hoping i'm following instructions, ... this is for Sesotho :  st/2018-03/01, i did not run compile.js as i'm not sure what it does. Please review and feedback.

### CODE REVIEW

**Comment by VitalikL** [comment]
Many thanks @RyzorBent . I will review this asap, however it looks like you are adding 1st lesson of the 3rd quarter. Do you have plan consistently adding Sesotho to make it up to date?

**Comment by RyzorBent** [comment]
HI @VitalikL, i'm planning to get it up to date in the next few days.

**Comment by imasaru** [comment]
@RyzorBent Hey Thabo! So you're finally helping out :wink: Nice!

What OS are you running?

**Comment by RyzorBent** [comment]
Hi, I’ve done all the weeks except st/2018-03/03, days 14-20 are missing from the site: https://www.sabbathschoolpersonalministries.org/international

I’ve sent them email and they responded, so I’m waiting on the translator.

Please check if all is good.

**Comment by VitalikL** [comment]
@RyzorBent This is strange that it's missing (pointing to different lesson). I am going to review this PR shortly. Hopefully there will be no issues with 4Q

**Comment by VitalikL** [comment]
@RyzorBent What is a good translation for Sesotho language?

**Comment by VitalikL** [comment]
I mean the actual Bible text. As you know we need it to embed Bible verses
detected in the text of Sabbath Schoo lesson

**Pull request merged**
