### PR TITLE
Add 3 and 4 in mg/2021-02

### PR DESCRIPTION
**Pull request by Slav7**
add 3 and 4
correct 1 and 2

### Pull Request check-list

_Please make sure to review and check all of these items:_

- [ ] Have you run `node compile.js -b test -l [language] -q [quarter]`?
- [ ] Have you checked for semicolons in the titles?

_NOTE: these things are not required to open a PR and can be done
afterwards / while the PR is open._

For example, `node compile.js -b test -l en -q 2018-02`.

### CODE REVIEW

**Comment by VitalikL** [comment]
Can you please run `./run.sh -q 2021-02 -l mg` locally and make sure the compilation script does not produce error. This is the way to verify that titles are correctly formatted. I am seeing that in Malagasy language there a lot of `'` characters.

**Comment by Slav7** [comment]
I have this error when runing this command :
./run.sh: line 21: docker: command not found

**Comment by VitalikL** [comment]
@Slav7 Yes, you need Docker installed on your machine

https://www.docker.com/products/docker-desktop

**Comment by Slav7** [comment]
I'm working on Windows git bash, I installed Docker and now when I run the command I have this error:
the input device is not a TTY.  If you are using mintty, try prefixing the command with 'winpty'

**Pull request closed without merging**
