### PR TITLE
Lithuanian laguage

### PR DESCRIPTION
**Pull request by gerizenklai**
Thought I will try to add Lithuanian language to the app.

### Pull Request check-list

_Please make sure to review and check all of these items:_

- [ ] Have you run `node compile.js -b test -l [language] -q [quarter]`?
- [x] Have you checked for semicolons in the titles?

_NOTE: these things are not required to open a PR and can be done
afterwards / while the PR is open._

For example, `node compile.js -b test -l en -q 2018-02`.

### CODE REVIEW

**Comment by VitalikL** [comment]
Thanks @gerizenklai for the PR- we would love to have a new language in the app!
Do you plan to support this language in future as well? 
Also it is better to add placeholders for all the lessons in advance. As for the new language you might need to take a look at `create.js` to add LT verisons of placeholder texts and then use to generate structure with proper dates and avoid manual creation because of higher chance of human error regarding correct dates and date ranges.

**Comment by gerizenklai** [comment]
> Thanks @gerizenklai for the PR- we would love to have a new language in the app!
> Do you plan to support this language in future as well?
> Also it is better to add placeholders for all the lessons in advance. As for the new language you might need to take a look at `create.js` to add LT verisons of placeholder texts and then use to generate structure with proper dates and avoid manual creation because of higher chance of human error regarding correct dates and date ranges.

Yes, Im planing to support this language in a future.
I will check placeholders

**Comment by gerizenklai** [comment]
should I continue or better to wait untill you aprove LT language contrubution?

**Comment by VitalikL** [comment]
Please continue. I am going to integrate the Lithuanian Bible and then merge

**Comment by gerizenklai** [comment]
@VitalikL We completed uploading all SS lessons. What is next? When could we expect to be able to use the app for SS in Lithuania?

**Comment by VitalikL** [comment]
Thanks. I am expecting to finish Bible prep sometime this week.

**Comment by VitalikL** [comment]
@gerizenklai I was able to find the Bible and going through parsing now!

**Pull request merged**
