### PR TITLE
Adding pt/2021-04/01 (first week of the fourth quarter of 2021 in Portuguese)

### PR DESCRIPTION
**Pull request by ArthurMota9**
### Pull Request check-list

_Please make sure to review and check all of these items:_

- [ ] Have you run `run.sh` or `node deploy.js -b test -l [language] -q [quarter]`?
- [ ] Have you checked for semicolons in the titles?

_NOTE: these things are not required to open a PR and can be done
afterwards / while the PR is open._

For example, `node deploy.js -b test -l en -q 2018-02`.

### Description of contribution
Adding pt/2021-04/01, which corresponds to the first week of the fourth quarter of 2021 in Portuguese.

I met the Sabbath School app last week through a friend and I was very happy to hear that you are open source. I've always had the desire to contribute to projects that are involved with the church and spreading the word of God.

I'm submitting this first week to ensure it's in the correct format and then I'll be submitting the other weeks.

### CODE REVIEW

**Comment by ArthurMota9** [comment]
Have you recently contacted CPB? Because today they make the lessons available for free through this site: https://mais.cpb.com.br/licao-adultos/

**Comment by kimtiago** [comment]
Now they have this http://cloud.mkt.cpb.com.br/sac

**Comment by eltoncezar** [comment]
Hi, any news on this? The Portuguese translation seems available on my app, but I can't find it in the repo.

**Comment by eltoncezar** [comment]
Thanks @VitalikL! This is official now? I mean, no more legal problems?

**Comment by VitalikL** [comment]
@eltoncezar Correct!

**Comment by ArthurMota9** [comment]
Good news!! So now we can contribute by including more lessons, right? @VitalikL

**Comment by VitalikL** [comment]
@ArthurMota9 Yes, since the app is now official app we got the permission. I would advise not to put Youth lesson yet, because we are still working on getting permission for that.

**Comment by kimtiago** [comment]
@VitalikL i saw you have been commit the portuguese lessons... where do you find this content? I want to help with this from now.

**Comment by VitalikL** [comment]
@kimtiago Since the app is now official GC app CPB is sending over the content in Adult and InVerse (Comtexto)

**Comment by VitalikL** [comment]
@ArthurMota9 also wanted to mention, that InVerse in Portuguese is now part of the app, we were able to get the permission. It is quite easy to add, since content that is sent to us is in original source, which we automate.

**Pull request closed without merging**
