### PR TITLE
En/2019-01-er (All Lessons)

### PR DESCRIPTION
**Pull request by clope031**
### Pull Request check-list

_Please make sure to review and check all of these items:_

- [ ] Have you run `node compile.js -b test -l [language] -q [quarter]`?
- [x] Have you checked for semicolons in the titles?

_NOTE: these things are not required to open a PR and can be done
afterwards / while the PR is open._

For example, `node compile.js -b test -l en -q 2018-02`.

### CODE REVIEW

**Comment by clope031** [comment]
I forgot I am missing image. I will look for one

**Comment by VitalikL** [comment]
Thanks @clope031 ! I only have one ask - can you remove the verses in brackets. I am not sure what is the purpose in the actual book, but the same verse is referenced in the actual lesson.

**Comment by clope031** [comment]
@VitalikL Done! Still not able to find Front Page

**Comment by VitalikL** [comment]
@clope031 No problem - will create one

**Pull request merged**
