### PR TITLE
Added ja/2020-02

### PR DESCRIPTION
**Pull request by imasaru**
### Pull Request check-list

_Please make sure to review and check all of these items:_

- [ ] Have you run `node compile.js -b test -l [language] -q [quarter]`?
- [ ] Have you checked the completed lessons for typographical errors?
- [x] Have you checked for semicolons in the titles?

_NOTE: these things are not required to open a PR and can be done
afterwards / while the PR is open._

### CODE REVIEW

**Comment by imasaru** [comment]
@VitalikL Ahh, boy... Misnamed that commit 2416c30

🤷‍♂️

**Comment by VitalikL** [comment]
@imasaru Not sure I follow, something wrong?

**Comment by imasaru** [comment]
image

Should've been ja/2020-**02**/01 😅

I get used to typing the same thing after a while—muscle memory!

**Comment by VitalikL** [comment]
Hahah, all good!

**Pull request merged**
