### PR TITLE
Added src\cs\2019-02 with czech lesson 05

### PR DESCRIPTION
**Pull request by tkacikr**
### Pull Request check-list

_Please make sure to review and check all of these items:_

- [x] Have you run `node compile.js -b test -l [language] -q [quarter]`?
- [x] Have you checked for semicolons in the titles?

_NOTE: these things are not required to open a PR and can be done
afterwards / while the PR is open._

For example, `node compile.js -b test -l en -q 2018-02`.

### CODE REVIEW

**Comment by tkacikr** [comment]
I made "node compile.js ..." - is OK.
If this czech lesson 05 is OK and will be in main Adventech:stage, I will do next czech lessons in future.

**Comment by VitalikL** [comment]
Thank you. I have already prepared and sorry for the delay with Czech language as I am on a mission trip.

**Comment by tkacikr** [comment]
Do you want help with Czech language lessons in future quarter? I can help you with that.

**Comment by tkacikr** [comment]
I look at lesson 5 and see some problems:
* Wrong date in lessons.
* info.yml in lesson 05 directory has wrong date too, and wrong title. It should be IMHO:
title: "Slova moudrosti pro rodiny"
start_date: "27/04/2019"
end_date: "03/05/2019"
* In info.yml in querter directory (2019-02) should be human_date as "Duben · Květen · Červen 2019".

**Comment by VitalikL** [comment]
You are right. Will fix that

**Pull request closed without merging**
