### PR TITLE
Adding sn/2024-01/07 - 13

### PR DESCRIPTION
**Pull request by nadchif**
### Pull Request check-list

_Please make sure to review and check all of these items:_

- [x] Have you run `run.sh` or `node deploy.js -b test -l [language] -q [quarter]`?
- [x] Have you checked for semicolons in the titles?

_NOTE: these things are not required to open a PR and can be done
afterwards / while the PR is open._

For example, `./run.sh -l en -q 2022-01` or `node deploy.js -b test -l en -q 2018-02`.

### CODE REVIEW

**Comment by nadchif** [comment]
Credits @muscamo. Thank you

**Comment by VitalikL** [comment]
Hello bro @nadchif - will you be able to add `Shona` for `2024-02`? Thank you!

**Comment by nadchif** [comment]
Yes yes @VitalikL 🙂 It's work in progress.

**Comment by VitalikL** [comment]
Great! Looking forward to it

**Comment by nadchif** [comment]
Hi @VitalikL please help make  the package `@Adventech/bible-tools` publicly accessible. We currently cannot run an `npm install`:

Screenshot 2024-04-06 at 7 21 59 PM

In the mean time, I used the old configuration to test it locally. Please find our Pull Request [here](https://github.com/Adventech/sabbath-school-lessons/pull/2760/)

Lessons 5-13 to follow.

cc @muscamo

Thank you 🙂

**Pull request merged**
