### PR TITLE
Adding src/de/2024-04/13/teacher-questions.md and previous

### PR DESCRIPTION
**Pull request by toak**
for adult lesson de/2024-04
from wiki.sabbatschule.at

### Pull Request check-list
_Please make sure to review and check all of these items:_
- [x] Have you checked for semicolons in the titles?

### CODE REVIEW

**Comment by toak** [comment]
@VitalikL This is for the current lesson in 2024, can you pls accept?

**Comment by toak** [comment]
I would really like to understand what's the issue with this PR. Is it the content?
The content of this pull request is advertised here: https://wiki.sabbatschule.at/index.php/Hauptseite

People are asking already why the content is no there...

**Comment by VitalikL** [comment]
@toak The main issue was with the formatting and our new API version v3, which does not support HTML. There was a small issue which we have already removed, which I am sure you are aware of. Sorry it was not merged on time, this new quarter it should be better, since I see the formatting looks good

**Comment by tobiawr** [comment]
@VitalikL Thanks for merging! I'm not sure if I'm aware of the issue, but I'm make sure that no HTML is used any more. I'll create another MR as there is more content available already.
Thanks so much and let me know if any changes need to be made.

**Comment by toak** [comment]
@VitalikL Thanks for merging! I'm not sure if I'm aware of the issue, but I'm make sure that no HTML is used any more. I'll create another MR as there is more content available already.
Thanks so much and let me know if any changes need to be made.

**Pull request merged**
