### PR TITLE
Added in/2020-04/02

### PR DESCRIPTION
**Pull request by animemoeus**
### Pull Request check-list

_Please make sure to review and check all of these items:_

- [ ] Have you run `node compile.js -b test -l [language] -q [quarter]`?
- [ ] Have you checked for semicolons in the titles?

_NOTE: these things are not required to open a PR and can be done
afterwards / while the PR is open._

For example, `node compile.js -b test -l en -q 2018-02`.

### CODE REVIEW

**Comment by VitalikL** [comment]
Thanks @animemoeus . Do you happen to have the full quarterly file?

**Comment by animemoeus** [comment]
Yes. I'm trying to get it over with as quickly as possible.

> Thanks @animemoeus . Do you happen to have the full quarterly file?

Yes. Now I am working on it. Hopefully, this can be done quickly.

**Comment by VitalikL** [comment]
That is awesome! Will you be able to email it to me as well? That way we
can do it quicker or perhaps I can take a look at the file and see if we
can automate the process.

**Comment by animemoeus** [comment]
Sorry, don't have that file. All I have is the Sabbath school book.

**Pull request merged**
