### PR TITLE
Fixed titles and cover for Ukrainian language in 2018-3

### PR DESCRIPTION
**Pull request by merlin-zaraza**

### CODE REVIEW

**Comment by VitalikL** [comment]
Thanks @merlin-zaraza !

**Comment by VitalikL** [comment]
Where do you get high quality cover images? @merlin-zaraza

**Comment by merlin-zaraza** [comment]
@VitalikL Kindly asking main editor Miroslav Dzhulay. I can send you his email.

**Comment by VitalikL** [comment]
Oh ok. I actually know him and got lesson frkm him too! Thanks.

**Pull request merged**
