### PR TITLE
InVerse will be available in German starting 3/2021.

### PR DESCRIPTION
**Pull request by toak**
de/2021-03-cq/01

### CODE REVIEW

**Comment by VitalikL** [comment]
@toak Very exciting news about German InVerse. One quick feedback regarding this PR - please generate the quarterly structure using `create.js` script to avoid manually entering dates, and it will also create skeleton for all the lessons.

**Comment by toak** [comment]
Ok, so even create them when they are empty? I wanted to used the create.js, but it created an error. I reported it #1562

**Comment by VitalikL** [comment]
@toak yes, empty is fine - we usually place text saying that the lessons are work in progress.

**Comment by toak** [comment]
The quarterly structure was created using create.js

**Comment by toak** [comment]
@VitalikL Can you pull it already for us to check the QR links? Right now we get a error page: https://sabbath-school.adventech.io/de/2021-03-cq/01/02

**Comment by VitalikL** [comment]
@toak It is actually possible for you to test locally. You will need to use `run.sh` script like that

```
./run.sh -q 2021-03-cq -l de
```

For that you will need to have `Docker` installed on your computer (http://docker.com). If everything is correct you will be able to access your local compiled version like this:

```
http://localhost:1313/de
```

**Comment by toak** [comment]
Thanks, @VitalikL, it´s not about testing.

It is about the QR codes in the lesson which point to the web-viewer in the Sabbath school lesson. As the pull request is still open, it leads people to an error page: https://sabbath-school.adventech.io/de/2021-03-cq/01/01

As the lessons are given out this week, without the pull request accepted, people will be wondering about the error message when they scan the QR code.

Can you please accept it?

**Comment by VitalikL** [comment]
I see. Yes, of course - will do it asap then. So you mean the QR code is
printed in physical lesson?

**Comment by toak** [comment]
@VitalikL: yes the QR codes are in the physical lesson. The physical lesson contains only the space for writing and instructions (inverse style). The QR code offers the text of the devotional version.

**Pull request merged**
