### PR TITLE
Adding fr/2021-01/ W13

### PR DESCRIPTION
**Pull request by clope031**
### Pull Request check-list

_Please make sure to review and check all of these items:_

- [ ] Have you run `node compile.js -b test -l [language] -q [quarter]`?
- [ ] Have you checked for semicolons in the titles?

_NOTE: these things are not required to open a PR and can be done
afterwards / while the PR is open._

For example, `node compile.js -b test -l en -q 2018-02`.

### CODE REVIEW

**Comment by VitalikL** [comment]
@clope031 Thanks

Just want to remind you about the formatting for the memory verse:

Your version: ```> **Verset à mémoriser**:<p></p>```
How it should be: ```> <p>Verset à mémoriser</p>```

**Comment by clope031** [comment]
Will do!

**Comment by VitalikL** [comment]
@clope031 When do you plan to do it?

**Comment by clope031** [comment]
@VitalikL 

Hello, Changed should be reflected now.

**Pull request merged**
