### PR TITLE
2021Q4_SS_Chi_20210906

### PR DESCRIPTION
**Pull request by eliasabbathschool**
### Pull Request check-list

_Please make sure to review and check all of these items:_

- [ ] Have you run `run.sh` or `node deploy.js -b test -l [language] -q [quarter]`?
- [x] Have you checked for semicolons in the titles?

_NOTE: these things are not required to open a PR and can be done
afterwards / while the PR is open._

For example, `node deploy.js -b test -l en -q 2018-02`.

### CODE REVIEW

**Comment by eliasabbathschool** [comment]
Elder V, I just would like to inform that the above conflicts have been solved.  Thank you for your kind attention.

**Comment by VitalikL** [comment]
Hi @eliasabbathschool! Thank you again for your contribution. Can you please fetch upstream (sync your fork). This article explains how to do it:

https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/syncing-a-fork

**Comment by eliasabbathschool** [comment]
I have just fetched upstream.  Please find if your stage can also be kept in sync.  Thank you very much.

**Comment by eliasabbathschool** [comment]
Although I see no conflicts when I sign in again after fetching upstream, please confirm if I rightly follow the procedure.  Thank you very much.

**Comment by VitalikL** [comment]
Thanks @eliasabbathschool . I can see the checks are successful now, which is a good thing. However, I do see that the Pull Request shows there are changes to `1191` files, which is of course related to your branch being out of sync for a long time. If I can ask you to close this Pull Request. Most importantly, sync the `stage` from your fork with the origin (fetch upstream) and reopen the PR. What I am looking for is for Pull Request to show correct number of files that are changed. It should be around `216` for two versions of Chinese Sabbath School.

**Comment by eliasabbathschool** [comment]
I actually remain all previous SS unchanged when I update every new quarter in Atom, not even a word.  However, branches of conflicts, which confuse me most, are always shown when I create pull request.  The only I can do is solving them for successful merging.  For handling the issue easily, should I firstly sync my stage (fetch upstream) before committing to yours?

**Comment by VitalikL** [comment]
@eliasabbathschool The easiest way is:

1. To close this Pull Request.
2. Fetch upstream from Github user interface.
3. Reopen Pull request.

In case if it does not work I can manually download your contribution and add to the app (How I did before).

**Comment by eliasabbathschool** [comment]
Elder V, I have just followed your given technique above.  It seems to work as all checks are still successful.  Thank you for giving me helping hands.

**Pull request closed without merging**
