### PR TITLE
es/2018-03-cq W7

### PR DESCRIPTION
**Pull request by clope031**
### Pull Request check-list

_Please make sure to review and check all of these items:_

- [ ] Have you run `node compile.js -b test -l [language] -q [quarter]`?
- [ ] Have you checked for semicolons in the titles?

_NOTE: these things are not required to open a PR and can be done
afterwards / while the PR is open._

For example, `node compile.js -b test -l en -q 2018-02`.

### CODE REVIEW

**Comment by VitalikL** [comment]
Thanks @clope031 ! Where did you find CQ version? Also, will you be able to add the remaining 1-6?

**Comment by clope031** [comment]
Hi @VitalikL, 

Is the actual website we seen previously. I found a snipping tool and use their text extract function plus doing several manual edits and spell checks. 

I will try to do 2 a week (1 future lesson and 1 past lesson).

**Comment by clope031** [comment]
Snipping tool is called SnagIt.

**Comment by VitalikL** [comment]
Understood.

**Pull request merged**
