### PR TITLE
W2 (2017 Q3)

### PR DESCRIPTION
**Pull request by imasaru**
The create.js script creates inside story placeholders even with `-i` as `false...`

### CODE REVIEW

**Comment by imasaru** [comment]
@VitalikL I have finished the lessons

**Comment by imasaru** [comment]
@VitalikL Sorry, I had to rebase my fork again... It is finally ready.

**Comment by VitalikL** [comment]
@imasaru we need empty placeholders to make sure ppl know we are working lessons if we dont have them. Also please separate PRs into two lessons and js changes

**Comment by imasaru** [comment]
Oh boy... That's right! What was I thinking...

**Comment by imasaru** [comment]
@VitalikL I am sorry. I have wasted your time again. This time, things are finally ready.

**Pull request merged**
