### PR TITLE
st/2018-03/03

### PR DESCRIPTION
**Pull request by RyzorBent**
### Pull Request check-list

_Please make sure to review and check all of these items:_

- [ ] Have you run `node compile.js -b test -l [language] -q [quarter]`?
- [ ] Have you checked for semicolons in the titles?

_NOTE: these things are not required to open a PR and can be done
afterwards / while the PR is open._

For example, `node compile.js -b test -l en -q 2018-02`.

### CODE REVIEW

**Comment by RyzorBent** [comment]
@VitalikL 
The bible can be downloaded as a jar from : http://m.bibles.co.za/index.php/mobile-bibles/sesotho/sesotho-19091961-so-complete/

or from this site: https://www.bible.com/bible/274/jhn.1.sso89so

**Comment by RyzorBent** [comment]
Hi, Guys,

Is there any help i can offer to speed up this PR?

Are you busy with the Bible parser?

**Comment by VitalikL** [comment]
@RyzorBent Yes, I am working on the Bible parser right now

**Comment by RyzorBent** [comment]
@VitalikL i'd like to assist regarding the parser, as i'm planning to work on Zulu and Xhosa next. Let me know how i can be involved on the bible parser.

**Comment by VitalikL** [comment]
I am almost done and should finish today. It also should apply to Zulu and
Xhosa Bibles!

**Comment by VitalikL** [comment]
Hi @RyzorBent . I have finished getting Sesotho Bible, however I noticed that Bible book names are different there from what I see in the lesson. For example, Genesis in bible.com is translated as "Tšimoloho" but I see "Genese" in the lesson. Do you happen to have the book names?

**Comment by RyzorBent** [comment]
@VitalikL take the book names from here: https://www.bible.com/bible/273/GEN.1.SSO61-SO

**Comment by VitalikL** [comment]
Thanks! I have already added, did you have a chance to look at it in the
app?

**Comment by RyzorBent** [comment]
I just checked on my app, 2.5.0 on iOS 12.0, ... the language is **not** there. I'm assuming on iOS the app automatically updates new additions?

**Comment by VitalikL** [comment]
Yes. Can you try reinstalling and see if it helps

**Comment by RyzorBent** [comment]
:+1: , re-install fixed the issue, Glad to see this published!

**Pull request merged**
