### PR TITLE
Added sn/2023-04

### PR DESCRIPTION
**Pull request by nadchif**
### Pull Request check-list

_Please make sure to review and check all of these items:_

- [x] Have you run `run.sh` or `node deploy.js -b test -l [language] -q [quarter]`?
- [x] Have you checked for semicolons in the titles?

_NOTE: these things are not required to open a PR and can be done
afterwards / while the PR is open._

For example, `./run.sh -l en -q 2022-01` or `node deploy.js -b test -l en -q 2018-02`.

### CODE REVIEW

**Comment by VitalikL** [comment]
Thank you very much @nadchif ! I will merge shortly. I am noticing that the cover comes from the original PDF. If you have the file we can also add it to the app (see English for example how it will look)

**Comment by nadchif** [comment]
Hi @nadchif just saw your message, Thank you for the clean up and changes done [here](https://github.com/Adventech/sabbath-school-lessons/commit/51bcc765bfdc8d2ba33668e1d348021cc31c7a04) 😄 

Unfortunately I do not have the original PDF, but I will try to get it. (cc @muscamo @thembimoyo2020)

On another note, would you know why on some days, the verses are not parsed into clickable links? I have been trying to fix that and can't seem to find the root cause yet 😕

**Comment by VitalikL** [comment]
@nadchif Yes, basically the Book names or abbreviations are probably not part of the book list in Shona (see https://github.com/Adventech/bible-tools/blob/master/lib/Bible-Passage-Reference-Parser/src/sn/data.txt). It is quite easy to add, simply add synonym in this file. You can fork and make PR for it. One thing to remember, the synonyms should be separated by the `TAB` character. Once you do the PR with just synonyms I can compile and update the parser. 

Alternatively (a bit more advanced) you can compile it yourself and PR the whole Shona Bible parser. You would need to run this command: `perl 01.add_lang.pl sn && perl 02.compile.pl sn` in the `lib/Bible-Passage-Reference-Parser/bin` folder. And commit all the files that are changed after running this command.

**Comment by nadchif** [comment]
@VitalikL thank you again. These are the steps I followed initially to add the Shona Bible. I also ensured that the book names I used in the translation were listed in [sn/data.txt](https://github.com/Adventech/bible-tools/blob/master/lib/Bible-Passage-Reference-Parser/src/sn/data.txt).

I will update and recompile the [sn/data.txt](https://github.com/Adventech/bible-tools/blob/master/lib/Bible-Passage-Reference-Parser/src/sn/data.txt).

Hoping for the best 🙂

**Comment by nadchif** [comment]
Thanks again @VitalikL. Done updating, opened a pull request in the Bible tools [here](https://github.com/Adventech/bible-tools/pull/77#issue-1947778525)

The error was coming down to the books I incorrectly named:

```bash
Error: ENOENT: no such file or directory, open 'adventech/sabbath-school-lessons/node_modules/adventech-bible-tools/bibles/sn/bdsc/books/05.js'
    at Object.openSync (node:fs:601:3)
    at Object.readFileSync (node:fs:469:35)
    at getBookByOSIS (adventech/sabbath-school-lessons/node_modules/adventech-bible-tools/bible_tools_bcv.js:40:27)
    at Object.search (adventech/sabbath-school-lessons/node_modules/adventech-bible-tools/bible_tools_bcv.js:92:29)
    at dayAPI (adventech/sabbath-school-lessons/deploy.js:706:33)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async adventech/sabbath-school-lessons/deploy.js:779:5 {
  errno: -2,
  syscall: 'open',
  code: 'ENOENT',
  path: 'adventech/sabbath-school-lessons/node_modules/adventech-bible-tools/bibles/sn/bdsc/books/05.js'
}
```

I've now renamed the first 9 books to have a `0` at the start. Like Genesis `1.js` -> `01.js`. It seems to be working 🙂 

Please help me know in case I've overlooked some things. Thanks 🙏

**Comment by VitalikL** [comment]
It looks fine and I merged it. Can confirm the Bible references work fine and the release should be up soon. Thank you 🙏

**Pull request merged**
