### PR TITLE
Added placeholder files for Q1 2018

### PR DESCRIPTION
**Pull request by PrJared**

### CODE REVIEW

**Comment by VitalikL** [comment]
@PrJared Did you create this PR by mistake?

**Comment by imasaru** [comment]
461 commits... It looks like using the `create.js` script didn't go too well for you :joy:

**Comment by PrJared** [comment]
I decided that since I was 461 commits ahead, I should make a pull request.  I went through and made placeholder files for all the lessons for Q1 2018.  I didn't know there was a file that automatically did it.  It took a while to do, but it should be correct.

**Comment by VitalikL** [comment]
@PrJared My suggestion to create new branch from `stage`, run `create.js` and then issue completely new PR

**Pull request closed without merging**
