### PR TITLE
Adding src/de/2018-03/05/teacher-questions.md

### PR DESCRIPTION
**Pull request by toak**
de/2018-03

from wiki.sabbatschule.at

### Pull Request check-list

_Please make sure to review and check all of these items:_

- [ ] Have you run ?
- [x] Have you checked for semicolons in the titles?

### CODE REVIEW

**Comment by VitalikL** [comment]
@toak thanks again! FYI you do not technically need to wait until the actual lesson is completed if you have teacher questions ready before that.

**Comment by toak** [comment]
@VitalikL thanks for the info. I do not wait. As soon as the questions are available, they get automatically converted and pushed once a day at 8pm cest.

**Comment by VitalikL** [comment]
Makes sense. Can you please change the auto PR to stage branch - this is
just in case in case of a build error so we don't affect production (that
happens sometimes). I will configure travis to merge stage to master daily
around 11pm EST.

**Comment by toak** [comment]
Is the auto merge by travis from stage to master already active?

**Pull request merged**
