### PR TITLE
added Georgian language and 4 lessons

### PR DESCRIPTION
**Pull request by DavidTbilisi**
### Pull Request check-list

_Please make sure to review and check all of these items:_

- [x] Have you run `node compile.js -b test -l [language] -q [quarter]`?
- [x] Have you checked for semicolons in the titles?

_NOTE: these things are not required to open a PR and can be done
afterwards / while the PR is open._

For example, `node compile.js -b test -l en -q 2018-02`.

### CODE REVIEW

**Comment by KeyJoo** [comment]
@DavidTbilisi 🚀 Awesome! 👍 🇬🇪

**Comment by KeyJoo** [comment]
Why you choose `ka` for `georgian-lang` and not `ge`?

**Comment by KeyJoo** [comment]
I finded answer myself here. 
- https://identity.adventist.org/downloads/logo/

**Comment by DavidTbilisi** [comment]
> @DavidTbilisi 🚀 Awesome! 👍 🇬🇪

thanks :)

**Comment by VitalikL** [comment]
@DavidTbilisi Looks like you have deleted `.github//PULL_REQUEST_TEMPLATE.md` in your commit - we need that :)

Also, I noticed that you are adding them progressively. It would be better if all 13 week structure will be there with placeholders for those lessons that are currently work in progress

**Comment by DavidTbilisi** [comment]
Ok, sorry for deleting ```PULL_REQUEST_TEMPLATE``` :) 
I have uploaded last two weeks, so it is complete now.
And is it mandatory to have `inside-story` and `teacher-comments` ?
because we don't have such.

**Comment by VitalikL** [comment]
@DavidTbilisi Nope, they are not mandatory. One last thing, is there a cover image for this quarterly because I see that you are using the Russian cover

**Pull request merged**
