### PR TITLE
Adding Sabbath School content zom/2020-02/01-13

### PR DESCRIPTION
**Pull request by kaixy1**
### Pull Request check-list

_Please make sure to review and check all of these items:_

- [x] Have you run `node compile.js -b test -l [language] -q [quarter]`?
- [x] Have you checked for semicolons in the titles?

_NOTE: these things are not required to open a PR and can be done
afterwards / while the PR is open._

For example, `node compile.js -b test -l en -q 2018-02`.

### CODE REVIEW

**Comment by VitalikL** [comment]
Thanks @kaixy1 . Will you be able to help with Bible books abbreviations?

**Comment by kaixy1** [comment]
@VitalikL I will help whatever needed. I just want to clarify. We want the Bible books not abbreviated so they are able to link with the Bible version (TDB)?  Sorry, this is my first time and I wanted to make sure I get it right. Thanks

**Comment by VitalikL** [comment]
Thanks @kaixy1 . Yes, we dont have to abbreviate them, however to make the verses clickable I will need the list of all Bible book names so we can parse them. Additionally I could not find the TDB version - do you have this Bible version or perhaps know where to get it?

**Comment by kaixy1** [comment]
[Bible_Book _TDB.txt](https://github.com/Adventech/sabbath-school-lessons/files/4431779/Bible_Book._TDB.txt)

**Comment by VitalikL** [comment]
Thank you @kaixy1 Do you have the actual Bible too?

**Comment by VitalikL** [comment]
Thank you @kaixy1. Would it make sense to use `ctd` as the language code for this?

**Comment by kaixy1** [comment]
@VitalikL I do not have a soft copy at this point and so far I can't seem to find one.  

Yes, ctd seems to be a better fit.

**Comment by VitalikL** [comment]
@kaixy1 Thanks. Can you also translate the strings in this file `web/config.toml`

**Comment by kaixy1** [comment]
@VitalikL Thanks.  I've translated most as I think some are better and clearer in English for the users.  I will make additional edits if I get user's request. 
Again, thanks for all your help.

**Pull request merged**
