### PR TITLE
Added et/2018-04

### PR DESCRIPTION
**Pull request by Ergas**
Looks like there is no inside story for this week :anguished:

### Pull Request check-list

_Please make sure to review and check all of these items:_

- [ ] Have you run `node compile.js -b test -l [language] -q [quarter]`?
- [ ] Have you checked for semicolons in the titles?

_NOTE: these things are not required to open a PR and can be done
afterwards / while the PR is open._

For example, `node compile.js -b test -l en -q 2018-02`.

### CODE REVIEW

**Comment by VitalikL** [comment]
Thanks @Ergas ! Do you happen to have a cover image for this quarter?

**Comment by Ergas** [comment]
No, not yet, I don't have evem PDF file. I can ask but I don't know if I
can get it yet or not.

**Comment by Ergas** [comment]
Hi,

I got now PDF file, so there you can find cover photo.

**Comment by Ergas** [comment]
received_2402883916418488

**Comment by VitalikL** [comment]
@Ergas Awesome! I am going to have to manually merge your commit as it is missing the remaining lessons with placeholders. Or if you want you can use `create.js` script to create structure for this quarter and add first lesson and the cover image.

**Comment by Ergas** [comment]
I will be ready with next quarter's SS lessons very soon, so You just need to **change colors**, I will do everything else. I hope to be ready before 30th September

**Comment by imasaru** [comment]
Tere hommikust @Ergas! Thank you for your contribution.

Thank you for following the guidelines with your commits. I'll just rename the PR to fit.

Aitäh.

**Pull request merged**
