### PR TITLE
kin 2023-01 

### PR DESCRIPTION
**Pull request by Burkifa23**
### Pull Request check-list

_Please make sure to review and check all of these items:_

- [x] Have you run `run.sh` or `node deploy.js -b test -l [language] -q [quarter]`?
- [x] Have you checked for semicolons in the titles?

### Description of contribution
I have added the 2023-01 up to the fifth week.

### CODE REVIEW

**Comment by VitalikL** [comment]
Ooops! Looks like you have to fix some issues before I can merge this PR
||Error description |
| ----------- | ----------- |
|🛑| Critical error. Can not parse the quarterly info: `src/kin/2023-01`/info.yml. Error: `YAMLException: bad indentation of a mapping entry (3:192)<br><br> 1 |  ... <br> 2 |  ... <br> 3 |  ... umvisha ubwabyo biraturenze!) "Nimurebe ukuntu Imana Data yaduk ...<br>-----------------------------------------^<br> 4 |  ... <br> 5 |  ... `|

**Comment by Burkifa23** [comment]
Greetings @VitalikL , 
I tried fixing the indentation problem at info.yml, however,
when I ran node deploy.js I received
Processing cover images
Processing misc images
Processing features images
Processing asset images
Deploying day API
Deploying lesson API
Deploying quarterly API
TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at getQuarterlyJSON (C:\Users\User\PycharmProjects\pythonProject\sabbath-school-lessons\deploy.js:301:28)
    at quarterlyAPI (C:\Users\User\PycharmProjects\pythonProject\sabbath-school-lessons\deploy.js:549:21)
    at C:\Users\User\PycharmProjects\pythonProject\sabbath-school-lessons\deploy.js:770:11
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

**Comment by VitalikL** [comment]
Hi @Burkifa23 , can you send me the Lesson text in Word or InDesign format?

**Comment by Burkifa23** [comment]
Greetings @***@***.*** ***@***.***>  I am sending you
the word doc. It is also already in the required format.
Thank you

**Comment by VitalikL** [comment]
Thank you @Burkifa23 ! I added based on your branch. In order for this to be an easy process, can you please `Sync your fork` in your GitHub. You can read more about that here: 

https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/syncing-a-fork

**Pull request closed without merging**
