### PR TITLE
kin/2024-01/02 upload

### PR DESCRIPTION
**Pull request by Burkifa23**
### Pull Request check-list

_Please make sure to review and check all of these items:_

- [x] Have you run `run.sh` or `node deploy.js -b test -l [language] -q [quarter]`?
- [x] Have you checked for semicolons in the titles?

### CODE REVIEW

**Comment by VitalikL** [comment]
Ooops! Looks like you have to fix some issues before I can merge this PR
||Error description |
| ----------- | ----------- |
|🛑| Potential error in the date field: `src/cs/2024-01/01/inside-story.md`. Expected: `05/01/2024`, got: `29/12/2023`|
|🛑| Potential error in the date field: `src/cs/2024-01/02/inside-story.md`. Expected: `12/01/2024`, got: `29/12/2023`|
|🛑| Potential error in the date field: `src/cs/2024-01/03/inside-story.md`. Expected: `19/01/2024`, got: `29/12/2023`|
|🛑| Potential error in the date field: `src/cs/2024-01/04/inside-story.md`. Expected: `26/01/2024`, got: `29/12/2023`|
|🛑| Potential error in the date field: `src/cs/2024-01/05/inside-story.md`. Expected: `02/02/2024`, got: `29/12/2023`|
|🛑| Potential error in the date field: `src/cs/2024-01/06/inside-story.md`. Expected: `09/02/2024`, got: `29/12/2023`|
|🛑| Potential error in the date field: `src/cs/2024-01/07/inside-story.md`. Expected: `16/02/2024`, got: `29/12/2023`|
|🛑| Potential error in the date field: `src/cs/2024-01/08/inside-story.md`. Expected: `23/02/2024`, got: `29/12/2023`|
|🛑| Potential error in the date field: `src/cs/2024-01/09/inside-story.md`. Expected: `01/03/2024`, got: `29/12/2023`|
|🛑| Potential error in the date field: `src/cs/2024-01/10/inside-story.md`. Expected: `08/03/2024`, got: `29/12/2023`|
|🛑| Potential error in the date field: `src/cs/2024-01/11/inside-story.md`. Expected: `15/03/2024`, got: `29/12/2023`|
|🛑| Potential error in the date field: `src/cs/2024-01/12/inside-story.md`. Expected: `22/03/2024`, got: `29/12/2023`|
|🛑| Potential error in the date field: `src/cs/2024-01/13/inside-story.md`. Expected: `29/03/2024`, got: `29/12/2023`|
|🛑| Potential error in the date field: `src/sk/2024-01/01/inside-story.md`. Expected: `05/01/2024`, got: `29/12/2023`|
|🛑| Potential error in the date field: `src/sk/2024-01/02/inside-story.md`. Expected: `12/01/2024`, got: `29/12/2023`|
|🛑| Potential error in the date field: `src/sk/2024-01/03/inside-story.md`. Expected: `19/01/2024`, got: `29/12/2023`|
|🛑| Potential error in the date field: `src/sk/2024-01/04/inside-story.md`. Expected: `26/01/2024`, got: `29/12/2023`|
|🛑| Potential error in the date field: `src/sk/2024-01/05/inside-story.md`. Expected: `02/02/2024`, got: `29/12/2023`|
|🛑| Potential error in the date field: `src/sk/2024-01/06/inside-story.md`. Expected: `09/02/2024`, got: `29/12/2023`|
|🛑| Potential error in the date field: `src/sk/2024-01/07/inside-story.md`. Expected: `16/02/2024`, got: `29/12/2023`|
|🛑| Potential error in the date field: `src/sk/2024-01/08/inside-story.md`. Expected: `23/02/2024`, got: `29/12/2023`|
|🛑| Potential error in the date field: `src/sk/2024-01/09/inside-story.md`. Expected: `01/03/2024`, got: `29/12/2023`|
|🛑| Potential error in the date field: `src/sk/2024-01/10/inside-story.md`. Expected: `08/03/2024`, got: `29/12/2023`|
|🛑| Potential error in the date field: `src/sk/2024-01/11/inside-story.md`. Expected: `15/03/2024`, got: `29/12/2023`|
|🛑| Potential error in the date field: `src/sk/2024-01/12/inside-story.md`. Expected: `22/03/2024`, got: `29/12/2023`|
|🛑| Potential error in the date field: `src/sk/2024-01/13/inside-story.md`. Expected: `29/03/2024`, got: `29/12/2023`|

**Comment by Burkifa23** [comment]
@VitalikL, Should Physically change these? Because these repositories are `cs` and `sk`. 
Or how should I solve this issue?

**Comment by Burkifa23** [comment]
Hello @VitalikL, 
I physically changed 29/12/2023 to the expected dates in both `cs` and `sk`. I ran `node deploy.js -b test -l cs -q 2024-01` and `node deploy.js -b test -l sk -q 2024-01`. It took about 10 seconds on `Deploying day API` as for the rest no more errors. It seems there might have been an error when creating the inside story files as the date was of last year's inside story date.

**Comment by VitalikL** [comment]
Sorry @Burkifa23 the changes were unrelated to your PR. Could you please revert your changes and I will be able to merge quickly. 

Thanks!

**Pull request closed without merging**
