### PR TITLE
Adding en/2020-01-er/ W2

### PR DESCRIPTION
**Pull request by clope031**
### Pull Request check-list

_Please make sure to review and check all of these items:_

- [ ] Have you run `node compile.js -b test -l [language] -q [quarter]`?
- [ ] Have you checked for semicolons in the titles?

_NOTE: these things are not required to open a PR and can be done
afterwards / while the PR is open._

For example, `node compile.js -b test -l en -q 2018-02`.

### CODE REVIEW

**Comment by clope031** [comment]
Need to fix date format....

**Comment by VitalikL** [comment]
@clope031 Take a look at the Memory verse and Reading formatting on Sabbath

**Comment by clope031** [comment]
@vitalikl will do... Tried to automate this quarter but I should have known it was too good to be true. Hahaha

**Comment by clope031** [comment]
@VitalikL I believe it should be ok now.

**Pull request merged**
