### PR TITLE
Adding src/de/2021-03/12/teacher-questions.md

### PR DESCRIPTION
**Pull request by toak**
de/2021-03

from wiki.sabbatschule.at

### Pull Request check-list

_Please make sure to review and check all of these items:_

- [x] Have you run ?
- [x] Have you checked for semicolons in the titles?

### CODE REVIEW

**Comment by VitalikL** [comment]
Ooops! Looks like you have to fix some issues before I can merge this PR
||Error description |
| ----------- | ----------- |
|🛑| Potential error in the date field: `src/de/2021-03/05/teacher-questions.md`. Expected: `30/07/2021`, got: `30/08/2021`|
|🛑| Potential error in the date field: `src/de/2021-03/09/teacher-questions.md`. Expected: `27/08/2021`, got: `03/09/2021`|
|🛑| Potential error in the date field: `src/de/2021-03/10/teacher-questions.md`. Expected: `03/09/2021`, got: `10/09/2021`|
|🛑| Potential error in the date field: `src/de/2021-03/11/teacher-questions.md`. Expected: `10/09/2021`, got: `17/09/2021`|
|🛑| Potential error in the date field: `src/de/2021-03/12/teacher-questions.md`. Expected: `17/09/2021`, got: `24/09/2021`|
|🛑| Potential error in the date field: `src/de/2021-03/13/teacher-questions.md`. Expected: `24/09/2021`, got: `24/07/2021`|

**Comment by VitalikL** [comment]
Ooops! Looks like you have to fix some issues before I can merge this PR
||Error description |
| ----------- | ----------- |
|🛑| Potential error in the date field: `src/de/2021-03/05/teacher-questions.md`. Expected: `30/07/2021`, got: `30/08/2021`|
|🛑| Potential error in the date field: `src/de/2021-03/09/teacher-questions.md`. Expected: `27/08/2021`, got: `03/09/2021`|
|🛑| Potential error in the date field: `src/de/2021-03/10/teacher-questions.md`. Expected: `03/09/2021`, got: `10/09/2021`|
|🛑| Potential error in the date field: `src/de/2021-03/11/teacher-questions.md`. Expected: `10/09/2021`, got: `17/09/2021`|
|🛑| Potential error in the date field: `src/de/2021-03/12/teacher-questions.md`. Expected: `17/09/2021`, got: `24/09/2021`|
|🛑| Potential error in the date field: `src/de/2021-03/13/teacher-questions.md`. Expected: `24/09/2021`, got: `24/07/2021`|

**Comment by VitalikL** [comment]
@toak Can you please fetch upstream and then recreate the PR. We added automated error detection system and looks like some dates are wrong in the the files you are committing.

**Comment by VitalikL** [comment]
Ooops! Looks like you have to fix some issues before I can merge this PR
||Error description |
| ----------- | ----------- |
|🛑| Potential error in the date field: `src/de/2021-03/09/teacher-questions.md`. Expected: `27/08/2021`, got: `03/09/2021`|
|🛑| Potential error in the date field: `src/de/2021-03/10/teacher-questions.md`. Expected: `03/09/2021`, got: `10/09/2021`|
|🛑| Potential error in the date field: `src/de/2021-03/11/teacher-questions.md`. Expected: `10/09/2021`, got: `17/09/2021`|
|🛑| Potential error in the date field: `src/de/2021-03/12/teacher-questions.md`. Expected: `17/09/2021`, got: `24/09/2021`|

**Comment by VitalikL** [comment]
Ooops! Looks like you have to fix some issues before I can merge this PR
||Error description |
| ----------- | ----------- |
|🛑| Potential error in the date field: `src/de/2021-03/08/teacher-questions.md`. Expected: `20/08/2021`, got: `27/08/2021`|
|🛑| Potential error in the date field: `src/de/2021-03/09/teacher-questions.md`. Expected: `27/08/2021`, got: `03/09/2021`|
|🛑| Potential error in the date field: `src/de/2021-03/10/teacher-questions.md`. Expected: `03/09/2021`, got: `10/09/2021`|
|🛑| Potential error in the date field: `src/de/2021-03/11/teacher-questions.md`. Expected: `10/09/2021`, got: `17/09/2021`|
|🛑| Potential error in the date field: `src/de/2021-03/12/teacher-questions.md`. Expected: `17/09/2021`, got: `24/09/2021`|

**Comment by VitalikL** [comment]
Ooops! Looks like you have to fix some issues before I can merge this PR
||Error description |
| ----------- | ----------- |
|🛑| Potential error in the date field: `src/de/2021-03/08/teacher-questions.md`. Expected: `20/08/2021`, got: `27/08/2021`|

**Comment by toak** [comment]
> @toak Can you please fetch upstream and then recreate the PR. We added automated error detection system and looks like some dates are wrong in the the files you are committing.

Fixed the scripts, the dates are correct now

**Pull request merged**
