### PR TITLE
Add sn/2023-03

### PR DESCRIPTION
**Pull request by nadchif**
### Pull Request check-list

_Please make sure to review and check all of these items:_

- [x] Have you run `run.sh` or `node deploy.js -b test -l [language] -q [quarter]`?
- [x] Have you checked for semicolons in the titles?

_NOTE: these things are not required to open a PR and can be done
afterwards / while the PR is open._

For example, `./run.sh -l en -q 2022-01` or `node deploy.js -b test -l en -q 2018-02`.

### CODE REVIEW

**Comment by nadchif** [comment]
cc @thembimoyo2020 @dubehimself

**Comment by VitalikL** [comment]
Thanks @nadchif @thembimoyo2020 @dubehimself

This looks like a new language and thus it would be much better if we would have a Bible translation. Do you know if there is Bible translation available for Shona?

**Comment by nadchif** [comment]
Hi @VitalikL thank you for a prompt response. Yes it is a new language 😅

There are some shona bibles here:
- [Shona Bible 1949, revised 2002](https://www.bible.com/bible/1960/GEN.1.SNA2002)  
- [Bhaibheri Dzvene MuChiShona Chanhasi](https://www.bible.com/bible/32/GEN.1.BDSC)

**Comment by VitalikL** [comment]
Awesome @nadchif . The only thing I would mention is that the changes to `./web` are no longer necessary as we have moved to the `VueJS` app. If you can kindly provide translations to some strings in this repo:

https://github.com/Adventech/sabbath-school-web

**Comment by nadchif** [comment]
Yay! Absolutely @VitalikL. Let' me work on that right away.

Thank you 🙂

**Comment by VitalikL** [comment]
Hi @nadchif - Thanks for adding Shona last quarter, are you able to add 4Q 2023 as well?

**Comment by dchif** [comment]
Hi @VitalikL thank you 🙏 

we are currently working on it. Sorry for the delay 

We will be opening a pull request soon

**Comment by nadchif** [comment]
Thanks again @VitalikL. Done updating, opened a pull request in the Bible tools [here](https://github.com/Adventech/bible-tools/pull/77#issue-1947778525)

The error was coming down to the books I incorrectly named:

```bash
Error: ENOENT: no such file or directory, open 'adventech/sabbath-school-lessons/node_modules/adventech-bible-tools/bibles/sn/bdsc/books/05.js'
    at Object.openSync (node:fs:601:3)
    at Object.readFileSync (node:fs:469:35)
    at getBookByOSIS (adventech/sabbath-school-lessons/node_modules/adventech-bible-tools/bible_tools_bcv.js:40:27)
    at Object.search (adventech/sabbath-school-lessons/node_modules/adventech-bible-tools/bible_tools_bcv.js:92:29)
    at dayAPI (adventech/sabbath-school-lessons/deploy.js:706:33)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async adventech/sabbath-school-lessons/deploy.js:779:5 {
  errno: -2,
  syscall: 'open',
  code: 'ENOENT',
  path: 'adventech/sabbath-school-lessons/node_modules/adventech-bible-tools/bibles/sn/bdsc/books/05.js'
}
```

I've now renamed the first 9 books to have a `0` at the start. Like Genesis `1.js` -> `01.js`. It seems to be working 🙂 

Please help me know in case I've overlooked some things. Thanks 🙏

**Pull request merged**
