### PR TITLE
Adding Ikirundi

### PR DESCRIPTION
**Pull request by Burkifa23**
### Pull Request check-list
Greetings @VitalikL and the team,
Hope you are doing well.
I have added a new language from Burundi "Ikirundi" ISO 639: RUN
I have encountered same problems when running node deploy.
_Please make sure to review and check all of these items:_

- [x] Have you run `run.sh` or `node deploy.js -b test -l [language] -q [quarter]`?
- [x] Have you checked for semicolons in the titles?

### CODE REVIEW

**Comment by VitalikL** [comment]
Thanks @Burkifa23 ! Great to see new languages added to the app.

The problem here is that the language `run` is not added to the `config.js` which is the list of Bible translations that language uses. It is connected to this repo `https://github.com/Adventech/bible-tools`. In case if you do not have a Bible for that language, for now you can add empty array to the `config.js`.

**Comment by Burkifa23** [comment]
Greetings @VitalikL,
Thank you, I was able to fix the errors.

I was able to find only the New Testament versions of this language online. 
[RUN1967](https://www.bible.com/bible/2944/MAT.1.RUN1967)
[BKC](https://www.bible.com/bible/3264/MAT.1.BKC)
I found the the full bible version in an app.
[App](https://play.google.com/store/apps/details?id=bibiliyayera.ki&hl=en&gl=USl)

**Comment by Burkifa23** [comment]
Greetings @VitalikL ,
I have added the new version to the bible tools. Bibiliya Yera mu Kirundi(BKC). 
But I'll continue editing the bible version since there 66 books.

**Comment by Burkifa23** [comment]
Greetings @VitalikL,
The Merge branch failed yet I received  no errors when I run node run in my terminal? Please, how can I fix the problem with deploy- pdf/-video/-audio, deply and aggregator.

**Comment by VitalikL** [comment]
Hi @Burkifa23 - are you able to add 4Q in Ikirundi?

**Comment by Burkifa23** [comment]
Greetings @VitalikL, hope you are doing well. I received the pdf just now. I will work on uploading it ASAP.

**Pull request merged**
