### PR TITLE
Adding de/2020-01/01-06

### PR DESCRIPTION
**Pull request by andrucha97**
### Pull Request check-list

_Please make sure to review and check all of these items:_

- [x] Have you run `node compile.js -b test -l [language] -q [quarter]`?
- [x] Have you checked for semicolons in the titles?

_NOTE: these things are not required to open a PR and can be done
afterwards / while the PR is open._

For example, `node compile.js -b test -l en -q 2018-02`.

### Description of contribution

Lesson 01-06 is done. Soon more.

### CODE REVIEW

**Comment by imasaru** [comment]
Happy New Year @andrucha97  🎆 🎉

For your title, I think you may have meant to put `de/2020-01/06`

Thanks!

**Comment by andrucha97** [comment]
@imasaru oh wow. Yeah it was late. I changed it. I finished lesson 01-06

**Comment by imasaru** [comment]
> @imasaru oh wow. Yeah it was late. I changed it. I finished lesson 01-06

Thanks! Happens to me all the time, since I work late too 😆

**Comment by andrucha97** [comment]
@VitalikL wow that was close xD

**Pull request merged**
